import numpy as np
main_parameters = dict(preprocess_train_datasets=0,
                  preprocess_validation_datasets=0,
                  preprocess_test_datasets=0,
                  clean_sample_directories=0,
                  perform_validation_during_training=0,
                  perform_data_augmentation=True,
                  generate_point_cloud_vis=False,
                  load_existing_model=False,
                  num_epochs=3000,
                  learning_rate=0.000025,
                  fileset=None,
                  input_point_cloud=None,
                  model_filename='modelV1.pth',
                  box_dimens=np.array([2, 2, 2]),
                  box_overlap=[0.75, 0.75, 0.75],
                  min_points_per_box=1000,
                  max_points_per_box=20000,
                  subsample=False,
                  subsampling_min_spacing=0.01,
                  num_procs=34,
                  batch_size=4,
                  device='cpu')